name: Sonatype Workflow
on: push
jobs:
  sonatype-cli:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      # some steps are omitted...
      # Check out your code
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Sonatype GitHub Actions
        id: evaluate
      # You may pin to the exact commit or the version.
      # uses: sonatype/actions@0cd45a159282883b0592f035d55f75b5f270ff7f
        uses: sonatype/actions/evaluate@v1
        with: 
     # Lifecycle (IQ Server) URL (e.g. http://localhost:8070).
          iq-server-url: http://175.198.83.251:8070
    # The username to authenticate with Lifecycle (IQ Server).
          username: bjlee0312
    # The password to authenticate with Lifecycle (IQ Server).
          password: new!nectI0n
          
    # Lifecycle (IQ Server) application ID. When Automatic Applications is enabled and the application ID has not yet been used, a new application will be created with the given ID.
          application-id: SBOM_githubaction
    # Space-separated list of paths to specific files, directories, or docker images. Apache Ant-styled patterns are allowed.
          scan-targets: "**/*"
          upload-sarif-file: true
